### ISSUE TITLE
Customize the content of the received email

### ISSUE THREAD

**Issue by yenx2023** [rohit-chouhan/email_otp#4]
Hello, I would like to personalize the content of the email but no function seems to be available for this. Do you have an idea ?

**Comment by FaisalMohammadi** [comment]
Exactly i want the same functionality. Any update to this?

**Comment by ZahidUrRehman13** [comment]
i want the same functionality. Any update to this?

**Comment by rohit-chouhan** [comment]
Very soon, we will give that feature.

**Comment by ditikrimal** [comment]
Is it available now? I would like to edit the mail.

**Comment by rohit-chouhan** [comment]
yes already updated, now you can customize mail.

**Comment by ditikrimal** [comment]
Yeah I just checked it out and I was trying to use it. But whenever I try to use the custom template, no mail is sent but if I leave it to default template then the sending mail gives error.
![image](https://github.com/rohit-chouhan/email_otp/assets/96095778/9855ea67-58db-4f8b-b67e-e76059df0baf)
The error is like this. I suspected the error might be because of too much sending of mail or maybe because of the link in the default template (i.e to your website). So I wanted to use custom one. But while using the custom one neither it sends the mail nor it gives any error in my sending mailbox.

**Comment by ditikrimal** [comment]
Also I am new to flutter, Maybe my template is not being taken. Can you review my code. 
`import 'package:email_otp/email_otp.dart';

EmailOTP SendOTP(String email) {
  EmailOTP myauth = EmailOTP();

  myauth.setSMTP(
      host: "smtp.gmail.com",
      auth: true,
      username: "rml.ditik69@gmail.com",
      password: "puoorapmqqunupdh",
      secure: "TLS",
      port: 587);
  myauth.setConfig(
      appEmail: "rml.ditik69@gmail.com",
      appName: "My Notes",
      userEmail: email,
      otpLength: 6,
      otpType: OTPType.digitsOnly);
  var template = "<h1> Your OTP for login is <h1> <h3> {{otp}} </h3> ";
  myauth.setTemplate(render: template);
  if (myauth.sendOTP() == true) {
    return myauth;
  }
  return myauth;
}
`

**Comment by ditikrimal** [comment]
Also Can you Review my Code.
![image](https://github.com/rohit-chouhan/email_otp/assets/96095778/2f10b8a5-7e92-47bf-93a6-7a3e111c55fc)
